apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: sr
namePrefix: dev-
namespace: sr-ns
commonLabels:
  env: poc
resources:
  - yamls/configmap.yaml
  - yamls/cron-job.yaml
  - yamls/job.yaml
  - yamls/nginx-deployment.yaml
  - yamls/nginx-service.yaml
  - yamls/pv.yaml
  - yamls/pvc.yaml
  - yamls/secret.yaml
